CREATE TABLE CartBook (
    CartID VARCHAR(20) NOT NULL,
    BookID VARCHAR(20) NOT NULL,
    BookAmount INTEGER NOT NULL,
    CONSTRAINT CartBookPK PRIMARY KEY (CartID, BookID)
);

CREATE TABLE ShoppingCart (
    CartID VARCHAR(20) NOT NULL,
    AccountID VARCHAR(20) NOT NULL,
    CONSTRAINT ShoppingCartPK PRIMARY KEY (CartID)
);

CREATE TABLE AccountType (
    RoleID VARCHAR(20) NOT NULL,
    RoleName VARCHAR(30) NOT NULL,
    CONSTRAINT AccountTypePK PRIMARY KEY (RoleID)
);

CREATE TABLE Account (
    AccountID VARCHAR(20) NOT NULL,
    AccountName VARCHAR(50) NOT NULL,
    PasswordHash VARCHAR(100) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Fname VARCHAR(20) NOT NULL,
    Lname VARCHAR(20) NOT NULL,
    AccountRoleID VARCHAR(20),
    DiscountID VARCHAR(20),
    CONSTRAINT AccountPK PRIMARY KEY (AccountID)
);

CREATE TABLE AccountAddress (
    AccountID VARCHAR(20) NOT NULL,
    AddressID VARCHAR(20) NOT NULL,
    CONSTRAINT AccountAddressPK PRIMARY KEY (AccountID, AddressID)
);

CREATE TABLE AccountPhone (
    AccountID VARCHAR(20) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    CONSTRAINT AccountPhonePK PRIMARY KEY (AccountID)
);

CREATE TABLE Discount (
    DiscountID VARCHAR(20) NOT NULL,
    DiscountValue FLOAT NOT NULL,
    ExpiredDate DATE NOT NULL,
    CONSTRAINT DiscountPK PRIMARY KEY(DiscountID)
);

CREATE TABLE Review (
    ReviewID VARCHAR(20) NOT NULL,
    AccountID VARCHAR(20) NOT NULL,
    BookID VARCHAR(20) NOT NULL,
    Rating INTEGER NOT NULL,
    ReviewDate DATE NOT NULL,
    CONSTRAINT ReviewPK PRIMARY KEY (ReviewID)
);

CREATE TABLE Book (
    ISBN VARCHAR(20) NOT NULL,
    Title VARCHAR(50) NOT NULL,
    AuthorFName VARCHAR(20) NOT NULL,
    AuthorLName VARCHAR(20) NOT NULL,
    Edition VARCHAR(20) NOT NULL,
    Price FLOAT NOT NULL,
    AvailableAmount INTEGER NOT NULL,
    PublisherID VARCHAR(20),
    DepartmentID VARCHAR(20),
    DiscountID VARCHAR(20),
    CONSTRAINT BookPK PRIMARY KEY (ISBN)
);

CREATE TABLE BookGenre (
    ISBN VARCHAR(20) NOT NULL,
    GenreID VARCHAR(20) NOT NULL,
    CONSTRAINT BookGenrePK PRIMARY KEY (ISBN)
);

CREATE TABLE Publisher (
    PublisherID VARCHAR(20) NOT NULL,
    PublisherName VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    CONSTRAINT PublisherPK PRIMARY KEY (PublisherID)
);

CREATE TABLE PublisherAddress (
    PublisherID VARCHAR(20) NOT NULL,
    AddressID VARCHAR(20) NOT NULL,
    CONSTRAINT PublisherAddressPK PRIMARY KEY (PublisherID, AddressID)
);

CREATE TABLE Department (
    DepartmentID VARCHAR(20) NOT NULL,
    DepartmentName VARCHAR(20) NOT NULL,
    CONSTRAINT DepartmentPK PRIMARY KEY (DepartmentID)
);

CREATE TABLE Genre (
    GenreID VARCHAR(20) NOT NULL,
    GenreName VARCHAR(20) NOT NULL,
    CONSTRAINT GenrePK PRIMARY KEY (GenreID)
);

CREATE TABLE OrderHistory (
    OrderID VARCHAR(20) NOT NULL,
    CustomerID VARCHAR(20) NOT NULL,
    UseUserDiscount NUMBER(1) NOT NULL,
    IsPaid NUMBER(1) NOT NULL,
    IsShipped NUMBER(1) NOT NULL,
    AuditorID VARCHAR(20),
    OrderDate DATE NOT NULL,
    TotalPrice FLOAT NOT NULL,
    CONSTRAINT OrderHistoryPK PRIMARY KEY (OrderID)
);

CREATE TABLE OrderBook (
    OrderID VARCHAR(20) NOT NULL,
    BookID VARCHAR(20) NOT NULL,
    BookAmount INTEGER NOT NULL,
    CONSTRAINT OrderBookPK PRIMARY KEY (OrderID, BookID)
);

CREATE TABLE Shipment (
    ShipmentID VARCHAR(20) NOT NULL,
    ShipDate DATE NOT NULL,
    Fee FLOAT NOT NULL,
    AddressID VARCHAR(20) NOT NULL,
    OrderID VARCHAR(20) NOT NULL,
    CONSTRAINT ShipmentPK PRIMARY KEY (ShipmentID)
);

CREATE TABLE Payment (
    PaymentID VARCHAR(20) NOT NULL,
    PayDate DATE NOT NULL,
    PaymentTypeID VARCHAR(20),
    AddressID VARCHAR(20) NOT NULL,
    OrderID VARCHAR(20) NOT NULL,
    CONSTRAINT PaymentPK PRIMARY KEY (PaymentID)
);

CREATE TABLE BankAccount (
    PaymentTypeID VARCHAR(20) NOT NULL,
    AccountNumber VARCHAR(30) NOT NULL,
    ExpiredDate DATE NOT NULL,
    OwnerName VARCHAR(20) NOT NULL,
    CONSTRAINT BankAccountPK PRIMARY KEY (AccountNumber)
);

CREATE TABLE Giftcard (
    PaymentTypeID VARCHAR(20) NOT NULL,
    CardNumber VARCHAR(30) NOT NULL,
    Balance FLOAT NOT NULL,
    CONSTRAINT GiftcardPK PRIMARY KEY (CardNumber)
);

CREATE TABLE EPay (
    PaymentTypeID VARCHAR(20) NOT NULL,
    AccountNumber VARCHAR(20) NOT NULL,
    UserName VARCHAR(20) NOT NULL,
    CONSTRAINT EPayPK PRIMARY KEY (AccountNumber)
);

CREATE TABLE Address (
    AddressID VARCHAR(20) NOT NULL,
    Country VARCHAR(20) NOT NULL,
    State VARCHAR(20) NOT NULL,
    City VARCHAR(20) NOT NULL,
    Street VARCHAR(50) NOT NULL,
    PostalCode VARCHAR(20) NOT NULL,
    CONSTRAINT AddressPK PRIMARY KEY (AddressID)
);

CREATE TABLE AccountPaymentType (
    AccountID VARCHAR(20) NOT NULL,
    PaymentTypeID VARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT AccountPaymentTypePK PRIMARY KEY (AccountID)
);

ALTER TABLE CartBook ADD CONSTRAINT CartBookFKCartID FOREIGN KEY(CartID) REFERENCES ShoppingCart(CartID) ON DELETE CASCADE;

ALTER TABLE CartBook ADD CONSTRAINT CartBookFKBookID FOREIGN KEY(BookID) REFERENCES Book(ISBN) ON DELETE CASCADE;

ALTER TABLE ShoppingCart ADD CONSTRAINT ShoppingCartFKAccountID FOREIGN KEY(AccountID) REFERENCES Account(AccountID) ON DELETE CASCADE;

ALTER TABLE Account ADD CONSTRAINT AccountFKAccountRoleID FOREIGN KEY(AccountRoleID) REFERENCES AccountType(RoleID) ON DELETE SET NULL;

ALTER TABLE Account ADD CONSTRAINT AccountFKDiscountID FOREIGN KEY(DiscountID) REFERENCES Discount(DiscountID) ON DELETE SET NULL;

ALTER TABLE AccountAddress ADD CONSTRAINT AccountAddressFKAccountID FOREIGN KEY(AccountID) REFERENCES Account(AccountID) ON DELETE CASCADE;

ALTER TABLE AccountAddress ADD CONSTRAINT AccountAddressFKAddressID FOREIGN KEY(AddressID) REFERENCES Address(AddressID) ON DELETE CASCADE;

ALTER TABLE AccountPhone ADD CONSTRAINT AccountPhoneFKAccountID FOREIGN KEY(AccountID) REFERENCES Account(AccountID) ON DELETE CASCADE;

ALTER TABLE Review ADD CONSTRAINT ReviewFKAccountID FOREIGN KEY(AccountID) REFERENCES Account(AccountID) ON DELETE CASCADE;

ALTER TABLE Review ADD CONSTRAINT ReviewFKBookID FOREIGN KEY(BookID) REFERENCES Book(ISBN) ON DELETE CASCADE;

ALTER TABLE Book ADD CONSTRAINT BookFKPublisherID FOREIGN KEY(PublisherID) REFERENCES Publisher(PublisherID) ON DELETE SET NULL;

ALTER TABLE Book ADD CONSTRAINT BookFKDepartmentID FOREIGN KEY(DepartmentID) REFERENCES Department(DepartmentID) ON DELETE SET NULL;

ALTER TABLE Book ADD CONSTRAINT BookFKDiscountID FOREIGN KEY(DiscountID) REFERENCES Discount(DiscountID) ON DELETE SET NULL;

ALTER TABLE BookGenre ADD CONSTRAINT BookGenreFKISBN FOREIGN KEY(ISBN) REFERENCES Book(ISBN) ON DELETE CASCADE;

ALTER TABLE BookGenre ADD CONSTRAINT BookGenreFKGenreID FOREIGN KEY(GenreID) REFERENCES Genre(GenreID) ON DELETE CASCADE;

ALTER TABLE PublisherAddress ADD CONSTRAINT PublisherAddressFKPublisherID FOREIGN KEY(PublisherID) REFERENCES Publisher(PublisherID) ON DELETE CASCADE;

ALTER TABLE PublisherAddress ADD CONSTRAINT PublisherAddressFKAddressID FOREIGN KEY(AddressID) REFERENCES Address(AddressID) ON DELETE CASCADE;

ALTER TABLE OrderHistory ADD CONSTRAINT OrderHistoryFKCustomerID FOREIGN KEY(CustomerID) REFERENCES Account(AccountID) ON DELETE CASCADE;

ALTER TABLE OrderHistory ADD CONSTRAINT OrderHistoryFKAuditorID FOREIGN KEY(AuditorID) REFERENCES Account(AccountID) ON DELETE SET NULL;

ALTER TABLE OrderBook ADD CONSTRAINT OrderBookFKOrderID FOREIGN KEY(OrderID) REFERENCES OrderHistory(OrderID) ON DELETE CASCADE;

ALTER TABLE OrderBook ADD CONSTRAINT OrderBookFKBookID FOREIGN KEY(BookID) REFERENCES Book(ISBN) ON DELETE CASCADE;

ALTER TABLE Shipment ADD CONSTRAINT ShipmentFKAddressID FOREIGN KEY(AddressID) REFERENCES Address(AddressID) ON DELETE CASCADE;

ALTER TABLE Shipment ADD CONSTRAINT ShipmentFKOrderID FOREIGN KEY(OrderID) REFERENCES OrderHistory(OrderID) ON DELETE CASCADE;

ALTER TABLE Payment ADD CONSTRAINT PaymentFKAddressID FOREIGN KEY(AddressID) REFERENCES Address(AddressID) ON DELETE CASCADE;

ALTER TABLE Payment ADD CONSTRAINT PaymentFKOrderID FOREIGN KEY(OrderID) REFERENCES OrderHistory(OrderID) ON DELETE CASCADE;

ALTER TABLE Payment ADD CONSTRAINT PaymentFKPaymentTypeID FOREIGN KEY(PaymentTypeID) REFERENCES AccountPaymentType(PaymentTypeID) ON DELETE SET NULL;

ALTER TABLE BankAccount ADD CONSTRAINT BankAccountFKPaymentTypeID FOREIGN KEY(PaymentTypeID) REFERENCES AccountPaymentType(PaymentTypeID) ON DELETE CASCADE;

ALTER TABLE Giftcard ADD CONSTRAINT GiftcardFKPaymentTypeID FOREIGN KEY(PaymentTypeID) REFERENCES AccountPaymentType(PaymentTypeID) ON DELETE CASCADE;

ALTER TABLE EPay ADD CONSTRAINT EPayFKPaymentTypeID FOREIGN KEY(PaymentTypeID) REFERENCES AccountPaymentType(PaymentTypeID) ON DELETE CASCADE;

ALTER TABLE AccountPaymentType ADD CONSTRAINT AccountPaymentTypeFKAccountID FOREIGN KEY(AccountID) REFERENCES Account(AccountID) ON DELETE CASCADE;